from enum import Enum


class LedState(str, Enum):
    BOOTING = "BOOTING"
    IDLE = "IDLE"
    RECORDING = "RECORDING"
    TRANSCRIBING = "TRANSCRIBING"
    THINKING = "THINKING"
    SPEAKING = "SPEAKING"
    LOGGING = "LOGGING"
    ERROR = "ERROR"
    STOPPED = "STOPPED"
